### ISSUE TITLE
Missing sanitization callback function

### ISSUE THREAD

**Issue by x-bull** [aristath/kirki-helpers#17]
Theme check issue (include-kirki.php):
REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.

**Comment by aristath** [comment]
Fixed in https://github.com/aristath/kirki-helpers/commit/4c8ce6980df24d5b608427aee2bbde2e867be7f0
Added a dummy `'__return_true'` there just to stop the theme-checker from complaining.
This setting doesn't save anything anyway... there's no actual reason to add that callback other than to accommodate the checker.
